import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useRef } from 'react';
import { usePresence } from '../../../packages/presence-react/dist'

const Home: NextPage = () => {
  const { self, setState, peers } = usePresence("r1")
  const inputRef = useRef<any>()
  console.log('self:', self);
  console.log('peers:', peers);
  const clickHandle = ()=>{
    const el = inputRef.current
    if(el){
      setState({message:el.value})
      el.value = ''
    }
  }
  return (
    <div>
      <Head>
        <title>Presence Whthin Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>name:</div>
        <input ref={inputRef}/>
        <div>其他用户：</div>
        <div>{peers.map(({id, message}:any)=><div key={id}>{id}</div>)}</div>
      </div>
      <button onClick={clickHandle}>send</button>
    </div>
  )
}

export default Home
